### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Fungraphic** [cronzevid/triarb#1]
hi,
the command line for build not work.

![Capture d’écran_2020-12-01_19-06-13](https://user-images.githubusercontent.com/26345101/100779473-bf5f2b00-3408-11eb-803e-30f91babd474.png)

**Comment by cronzevid** [comment]
Hello,
It seems to be, that the problem is the way go treats packages. Original code was written under 1.11 which had [preliminary support for modules](https://blog.golang.org/using-go-modules). I've updated the code so it could compile under 1.16, please check it out.
Feel free to reopen if you face any issues
